-- ====================================================================
-- SAFE REPLACEMENT (security incident remediation, 2026-09-23)
--
-- The previous version of this file created a super-admin account directly in auth.users
-- with a password written in this file, added permissive RLS policies and made the private
-- gallery bucket public. It must never be run. It has been replaced by this file.
--
-- Supported way to set up a database and an admin:
--   1. Apply the schema:          npx supabase db push
--      (or, for a brand-new project only, run supabase/complete_setup.sql once)
--   2. Deploy the sign-in function: npx supabase functions deploy vault-auth --no-verify-jwt
--   3. Create the account in the app (normal sign-up; you choose the password; it is stored by
--      Supabase Auth as a bcrypt hash and never appears in this repository).
--   4. Promote it here, as the database owner (SQL editor):
--
--        select public.grant_super_admin('<username>', null);
--
--      grant_super_admin() only works on an account that already exists, cannot be executed by
--      anon, authenticated or service_role, and writes a GRANT_SUPER_ADMIN audit-log entry.
--      To remove admin rights:  select public.revoke_super_admin('<username>');
--
-- This file intentionally contains no schema, policies, buckets or accounts.
-- ====================================================================
select 'See the comments in this file. Nothing was changed.' as note;
